apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: dev
spec:
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      tier: backend
