apiVersion: v1
kind: Pod
metadata:
        name: helloworld
        labels:
                app: helloworld 
                type: back-end
                dev: hector
spec:
        containers:
                - name: hello-world
                  image: hello-world
